import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

import Image from "next/image";
import Homepage from "./homepage";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  /*  const wines = api.wines.getAll.useQuery();
  const grapes = api.grapes.getAll.useQuery();
  const createGrape = api.grapes.create.useMutation({
    async onSuccess() {
      await queryClient.invalidateQueries(grapes);
    },
  });

  const deleteGrape = api.grapes.delete.useMutation({
    async onSuccess() {
      await queryClient.invalidateQueries(grapes);
    },
  });

  const handleDeleteGrape = (id: string) => {
    deleteGrape.mutate({ id });
  };

  const handleClick = () => {
    createGrape.mutate({ name: input });
    setModalOpen(false);
  }; */
  return (
    <>
      <Head>
        <title>Ma petite Cave.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <Homepage />
      ) : (
        <div className="xy-center flex-col gap-5 p-3 pt-4">
          <p className="text-center text-4xl font-semibold">
            Welcome to your <br />
            grape-tastic app for wine storage fun. <br />
            <br /> Bottoms up!
          </p>
          <Image
            src="/images/CellarWine.png"
            alt="Bottle of wine"
            width={300}
            height={300}
            className="h-72 w-full rounded-md"
          />
        </div>
      )}
    </>
  );
};

export default Home;
